// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Petros;

{$R *.RES}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {vcl\QRABOUT.dfm}
{ITE} {DFMFileType} {vcl\QRCOMPED.dfm}
{ITE} {DFMFileType} {vcl\QRENVED.dfm}
{ITE} {DFMFileType} {vcl\QRLABLED.dfm}
{ITE} {DFMFileType} {vcl\QRPREV.dfm}
{ITE} {DFMFileType} {vcl\QRPRGRES.dfm}
{ITE} {DFMFileType} {D\PROGRAM FILES\DELPHI5\MEND\Mend_C.dfm}
{ITE} {DFMFileType} {D\PROGRAM FILES\DELPHI5\OBJREPOS\MROLLUP.dfm}
{ITE} {DFMFileType} {About.dfm}
{ITE} {DFMFileType} {AnalInput.dfm}
{ITE} {DFMFileType} {AnData.dfm}
{ITE} {DFMFileType} {ArrayRolls.dfm}
{ITE} {DFMFileType} {AtProc.dfm}
{ITE} {DFMFileType} {BandGr.dfm}
{ITE} {DFMFileType} {BBrowse.dfm}
{ITE} {DFMFileType} {Biblio.dfm}
{ITE} {DFMFileType} {BSQL.dfm}
{ITE} {DFMFileType} {ChangeClass.dfm}
{ITE} {DFMFileType} {Classif.dfm}
{ITE} {DFMFileType} {Correlat.dfm}
{ITE} {DFMFileType} {DebuS.dfm}
{ITE} {DFMFileType} {DeletDescr.dfm}
{ITE} {DFMFileType} {Devid.dfm}
{ITE} {DFMFileType} {Dictionar.dfm}
{ITE} {DFMFileType} {Distance.dfm}
{ITE} {DFMFileType} {DMod1.dfm}
{ITE} {DFMFileType} {EdBook.dfm}
{ITE} {DFMFileType} {EdCoefs.dfm}
{ITE} {DFMFileType} {ExcelExp.dfm}
{ITE} {DFMFileType} {explor.dfm}
{ITE} {DFMFileType} {Grouping.dfm}
{ITE} {DFMFileType} {ImpLookUps.dfm}
{ITE} {DFMFileType} {ImportAn.dfm}
{ITE} {DFMFileType} {ImpWiz.dfm}
{ITE} {DFMFileType} {Koeff.dfm}
{ITE} {DFMFileType} {ListBrows.dfm}
{ITE} {DFMFileType} {Lists.dfm}
{ITE} {DFMFileType} {LoadPr.dfm}
{ITE} {DFMFileType} {LookUps.dfm}
{ITE} {DFMFileType} {MAIN.dfm}
{ITE} {DFMFileType} {NewArr.dfm}
{ITE} {DFMFileType} {okcancl1.dfm}
{ITE} {DFMFileType} {Options.dfm}
{ITE} {DFMFileType} {ORF.dfm}
{ITE} {DFMFileType} {PetDBUtils.dfm}
{ITE} {DFMFileType} {Recalc.dfm}
{ITE} {DFMFileType} {RecResult.dfm}
{ITE} {DFMFileType} {Registrat.dfm}
{ITE} {DFMFileType} {Regres.dfm}
{ITE} {DFMFileType} {RepLstViewUnit.dfm}
{ITE} {DFMFileType} {RHABrows.dfm}
{ITE} {DFMFileType} {RHAColor.dfm}
{ITE} {DFMFileType} {RollQuery.dfm}
{ITE} {DFMFileType} {SelPoint.dfm}
{ITE} {DFMFileType} {SGridPrint.dfm}
{ITE} {DFMFileType} {Spaider.dfm}
{ITE} {DFMFileType} {Splash.dfm}
{ITE} {DFMFileType} {Stat.dfm}
{ITE} {DFMFileType} {StDiagProp.dfm}
{ITE} {DFMFileType} {StDiagrams.dfm}
{ITE} {DFMFileType} {Storage.dfm}
{ITE} {DFMFileType} {StRecalc.dfm}
{ITE} {DFMFileType} {TabMend.dfm}
{ITE} {DFMFileType} {Tasks.dfm}
{ITE} {DFMFileType} {TaskSQL.dfm}
{ITE} {DFMFileType} {TrioGraph.dfm}
{ITE} {DFMFileType} {TxtImpExp.dfm}
{ITE} {DFMFileType} {ViewSQ.dfm}
{ITE} {DFMFileType} {wait.dfm}
{ITE} {DFMFileType} {D\PROGRAM FILES\DELPHI5\TRIO\ChartProp.dfm}
{ITE} {DFMFileType} {D\PROGRAM FILES\DELPHI5\TRIO\Preview.dfm}
{ITE} {RCFileType} {Petros_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'vcl\QRABOUT.dfm' QRAboutBox:TForm(Form)}
{$R 'vcl\QRCOMPED.dfm' QRCompEd:TForm(Form)}
{$R 'vcl\QRENVED.dfm' QREnvironmentEditor:TForm(Form)}
{$R 'vcl\QRLABLED.dfm' QRLabelEditorForm:TForm(Form)}
{$R 'vcl\QRPREV.dfm' QRStandardPreview:TForm(Form)}
{$R 'vcl\QRPRGRES.dfm' QRProgressForm:TForm(Form)}
{$R 'D\PROGRAM FILES\DELPHI5\MEND\Mend_C.dfm' MendTabl:TControlGroupBox}
{$R 'D\PROGRAM FILES\DELPHI5\OBJREPOS\MROLLUP.dfm' RollsUp:TForm}
{$R 'About.dfm' About1:TForm}
{$R 'AnalInput.dfm' AnDlg:TForm}
{$R 'AnData.dfm' AnalForm:TForm}
{$R 'ArrayRolls.dfm' ArrayRollsUp:TForm(RollsUp)}
{$R 'AtProc.dfm' AtForm:TForm}
{$R 'BandGr.dfm' BandForm:TForm}
{$R 'BBrowse.dfm' BiblBrouse:TForm}
{$R 'Biblio.dfm' Books:TForm}
{$R 'BSQL.dfm' BiblSQL:TForm}
{$R 'ChangeClass.dfm' ChangeClForm:TForm}
{$R 'Classif.dfm' FClass:TForm}
{$R 'Correlat.dfm' CorrForm:TForm}
{$R 'DebuS.dfm' DebugSQL:TForm}
{$R 'DeletDescr.dfm' DeletDial:TForm}
{$R 'Devid.dfm' DevForm:TForm}
{$R 'Dictionar.dfm' SinonimForm:TForm}
{$R 'Distance.dfm' fDistance:TForm}
{$R 'DMod1.dfm' DM1:TDataModule}
{$R 'EdBook.dfm' EdBookForm:TForm}
{$R 'EdCoefs.dfm' EdKoefForm:TForm}
{$R 'ExcelExp.dfm' ExcF:TForm}
{$R 'explor.dfm' ClassForm:TForm}
{$R 'Grouping.dfm' GroupForm:TForm}
{$R 'ImpLookUps.dfm' ImpLookUpForm:TForm}
{$R 'ImportAn.dfm' ImportDialog:TForm}
{$R 'ImpWiz.dfm' WizForm:TForm}
{$R 'Koeff.dfm' KoefForm:TForm}
{$R 'ListBrows.dfm' LBrowseForm:TForm(RollsUp)}
{$R 'Lists.dfm' ListsRoll:TForm(RollsUp)}
{$R 'LoadPr.dfm' LoadPrForm:TForm}
{$R 'LookUps.dfm' LookUpForm:TForm}
{$R 'MAIN.dfm' MainForm:TForm}
{$R 'NewArr.dfm' DlNew:TForm}
{$R 'okcancl1.dfm' OKBottomDlg:TForm}
{$R 'Options.dfm' ConfigDlg:TForm}
{$R 'ORF.dfm' ORFForm:TForm}
{$R 'PetDBUtils.dfm' DbUtil:TForm}
{$R 'Recalc.dfm' AlgoForm:TForm}
{$R 'RecResult.dfm' RecResForm:TForm}
{$R 'Registrat.dfm' RegistrForm:TForm}
{$R 'Regres.dfm' RegrForm:TForm}
{$R 'RepLstViewUnit.dfm' RepLstViewFrm:TForm}
{$R 'RHABrows.dfm' FBrows:TForm}
{$R 'RHAColor.dfm' fRHAColor:TForm}
{$R 'RollQuery.dfm' QueryRolls:TForm(RollsUp)}
{$R 'SelPoint.dfm' SelForm:TForm}
{$R 'SGridPrint.dfm' fQRep:TForm}
{$R 'Spaider.dfm' SPForm:TForm}
{$R 'Splash.dfm' SForm:TForm}
{$R 'Stat.dfm' StatForm:TForm}
{$R 'StDiagProp.dfm' NewDiagr:TForm}
{$R 'StDiagrams.dfm' StDiaForm:TForm(OKBottomDlg)}
{$R 'Storage.dfm' StorageForm:TForm}
{$R 'StRecalc.dfm' RecForm:TForm}
{$R 'TabMend.dfm' MendForm:TForm}
{$R 'Tasks.dfm' NewProject:TForm}
{$R 'TaskSQL.dfm' TaskSQLForm:TForm}
{$R 'TrioGraph.dfm' TrioForm:TForm}
{$R 'TxtImpExp.dfm' ExptoTextForm:TForm}
{$R 'ViewSQ.dfm' SQView:TForm}
{$R 'wait.dfm' WForm:TForm}
{$R 'D\PROGRAM FILES\DELPHI5\TRIO\ChartProp.dfm' ChartPropertyForm:TForm}
{$R 'D\PROGRAM FILES\DELPHI5\TRIO\Preview.dfm' PrevForm:TForm}
{$R 'Petros_DRC.res' 'Petros_DRC.rc'}

{$E rus}

begin
end.